POST   http://localhost:3000/v1/anno1800/operations/calculate
Content-Type: application/json

{
"Shepherds":2
}

###

POST http://localhost:3000/v1/anno1800/operations/optimize
Content-Type: application/json

{
  "data": [
    {
      "guid": 114456,
      "amount": 1,
      "productivity": 1,
      "totalTpMin": 0.006
    }
  ]
}
