POST   http://localhost:3000/needs/de/calculate
Content-Type: application/json

{
"Shepherds":250
}

###

POST http://localhost:3000/needs/de/optimize
Content-Type: application/json

{
    "guid": 114444,
    "amount": 1,
    "productivity": 1,
    "totalTpMin": 0.525
}

###

GET http://localhost:3000/needs/metadata/populations
