POST   http://localhost:3000/needs/de/calculate
Content-Type: application/json

{
"Shepherds":2
}

###

POST http://localhost:3000/needs/de/optimize
Content-Type: application/json

{
  "data": [
    {
      "guid": 114456,
      "amount": 1,
      "productivity": 1,
      "totalTpMin": 0.006
    }
  ]
}

###

GET http://localhost:3000/needs/metadata/populations
